apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ##PREFIX##-ui-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2   
    # cert-manager.io/issuer: "letsencrypt-prod"
    # external-dns.alpha.kubernetes.io/hostname: ingress-external-dns2.oracloud.be 
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /##PREFIX##(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: ##PREFIX##-ui-service
                port:
                  number: 80
