micronaut:
  application:
    name: demo
{%- if db_family !="none" %}
datasources:
  default:
    url: ${JDBC_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driverClassName: {{ jdbcDriverClassName  }}
    {%- if db_family == "oracle" %}
    db-type: oracle
    dialect: oracle
    {%- elif db_family == "mysql" %}
    dialect: mysql
    {%- endif %}
{%- endif %}
netty:
  default:
    allocator:
      max-order: 3
jpa:
  default:
    entity-scan:
      packages: 'com.example'
