version: 0.1
component: build
timeoutInSeconds: 28000
runAs: root
shell: bash
env:
  exportedVariables:
    - BUILDRUN_HASH

steps:

  - type: Command
    name: "Build and Deploy using the build.sh script"
    timeoutInSeconds: 28000
    command: |
      yum install -y jq; oci iam compartment list; env; ls -al; ./build.sh
