apiVersion: apps/v1
kind: Deployment
metadata:
  name: ##PREFIX##-dep
  labels:
      app: ##PREFIX##-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ##PREFIX##-app
  template:
    metadata:
      labels:
        app: ##PREFIX##-app
    spec:
      containers:
      - name: app
        image: ##DOCKER_PREFIX##/##PREFIX##-app
        ports:
        - containerPort: 8080
          name: app-port
        env:
{%- if language == "java" %}
{%- if java_framework == "helidon" or java_framework == "helidon4" %}
        - name: JAVAX_SQL_DATASOURCE_DS1_DATASOURCE_URL
          valueFrom:
            secretKeyRef:
              name: ##PREFIX##-db-secret
              key: jdbc_url
{%- else %}        
{%- if java_framework == "springboot" %}
    - name: SPRING_APPLICATION_JSON
      valueFrom:
        secretKeyRef:
          name: ##PREFIX##-db-secret
          key: spring_application_json
{%- endif %}        
        - name: JDBC_URL
          valueFrom:
            secretKeyRef:
              name: ##PREFIX##-db-secret
              key: jdbc_url
{%- endif %}        
{%- else %}        
        - name: DB_URL
          valueFrom:
            secretKeyRef:
              name: ##PREFIX##-db-secret
              key: db_url
{%- endif %}        
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: ##PREFIX##-db-secret
              key: db_user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ##PREFIX##-db-secret
              key: db_password
      imagePullSecrets:
      - name: ocirsecret        
---
apiVersion: v1
kind: Service
metadata:
  name: ##PREFIX##-app-service
spec:
  selector:
    app: ##PREFIX##-app
  ports:
  - name: http-service-port
    protocol: TCP
    port: 80
    targetPort: app-port
---