FROM docker.io/library/nginx

# Copy the HTML files
COPY html/ /usr/share/nginx/html

{%- if deploy_type == "hosted_app" %}
COPY nginx_hosted_app.conf /etc/nginx/conf.d/default.conf
EXPOSE 8080
{%- endif %}
