# Build.tf

locals {
  project_dir = (var.infra_as_code=="from_resource_manager")?".":"../.."
}

# SSH Keys + tf_env.sh
resource "null_resource" "tf_env" {
  provisioner "local-exec" {
    command = <<-EOT
    cd ${local.project_dir}
    mkdir -p target
    # Create the files needed by the shell scripts
    # Create SSH Key
    echo "${local.ssh_public_key}" > target/ssh_key_starter.pub
    echo "${local.ssh_private_key}" > target/ssh_key_starter
    chmod 600 target/ssh_key_starter.pub
    chmod 600 target/ssh_key_starter
    
    # Create target/tf_env.sh
    ENV_FILE=target/tf_env.sh
    echo "# Generated by terraform - build.tf" > $ENV_FILE
    echo "" >> $ENV_FILE
    echo "# Terraform Variables" >> $ENV_FILE
    echo_export() {
      if [ "$2" != "" ] && [ "$2" != "-" ]; then
        echo "export $1=\"$2\"" >> $ENV_FILE
      fi 
    }
{%- for param in to_fill_params %}
{%- if param in terraform_variables %}
    echo_export "TF_VAR_{{param}}" "${coalesce(var.{{param}},"-")}"
{%- else %} 
    echo "# {{param}} declared in to_fill_params but not a terraform variable" >> $ENV_FILE
{%- endif %} 
{%- endfor %}  
    echo "# Terraform Locals" >> $ENV_FILE
{%- for key in terraform_locals %}
    echo_export "{{key.upper()}}" "${local.local_{{key}}}"
{%- endfor %} 
    echo "# Fixed" >> $ENV_FILE   
{%- for param in fixed_params %}
    echo_export "TF_VAR_{{param}}" "{{ params[param] }}"
{%- endfor %}
    echo "# Region" >> $ENV_FILE   
    echo "curl -s -H 'Authorization: Bearer Oracle' -L http://169.254.169.254/opc/v2/instance/ > /tmp/instance.json" >> $ENV_FILE   
    echo "export TF_VAR_region=`cat /tmp/instance.json | jq -r .region`" >> $ENV_FILE   
    echo "# Database" >> $ENV_FILE   
    echo "export DB_USER=\$TF_VAR_db_user" >> $ENV_FILE   
    echo "export DB_PASSWORD=\$TF_VAR_db_password" >> $ENV_FILE   
    # echo_export "OCI_STARTER_CREATION_DATE" "{{ create_datetime }}"
    # echo_export "OCI_STARTER_VERSION" "4.2"
    # echo_export "OCI_STARTER_PARAMS" "{{ params["params"] }}"
    chmod 755 $ENV_FILE
    EOT
  }
  triggers = {
    always_run = "${timestamp()}"
  }     
}

## BUILD_DEPLOY
resource "null_resource" "build_deploy" {
  provisioner "local-exec" {
    command = <<-EOT
        cd ${local.project_dir}
        export CALLED_BY_TERRAFORM="true"
        . ./starter.sh env        
        # pwd
        # ls -al target
        # cat target/terraform.tfstate
        # export
        # Run config command on the DB directly (ex RAC)
{%- if db_subtype == "rac" %}
        src/app/db/deploy_rac.sh
        exit_on_error "Deploy RAC"
{%- endif %}

        # Init target/compute
        if is_deploy_compute; then
            mkdir -p target/compute
            cp -r src/compute target/compute/.
        elif [ "$TF_VAR_deploy_type" == "kubernetes" ]; then
            $BIN_DIR/config_oke.sh
            exit_on_error "Deploy $TF_VAR_deploy_type"        
        fi

        # Build all apps
        if [ "$TF_VAR_build_host" == "terraform" ]; then
            for APP_NAME in `app_name_list`; do
                title "Build App $APP_NAME"
                src/app/build_$APP_NAME.sh
                exit_on_error "Build App $APP_NAME"
            done
        fi 

        # Build the DB tables (via Bastion)
        if [ -d src/app/db ] || [ "$TF_VAR_deploy_type" == "public_compute" ]; then
            title "Deploy Bastion"
            $BIN_DIR/deploy_bastion.sh
            exit_on_error "Deploy Bastion"   
        fi  

        # Deploy
        title "Deploy $TF_VAR_deploy_type"
        if [ "$TF_VAR_deploy_type" == "public_compute" ]; then
            echo "Skipping. Done via Deploy Bastion."
        elif [ "$TF_VAR_deploy_type" == "private_compute" ] || [ "$TF_VAR_deploy_type" == "instance_pool" ]; then
            $BIN_DIR/deploy_compute.sh
            exit_on_error "Deploy $TF_VAR_deploy_type"
        elif [ "$TF_VAR_deploy_type" == "container_instance" ]; then
            $BIN_DIR/deploy_ci.sh
            exit_on_error "Deploy $TF_VAR_deploy_type"
        fi
        ./starter.sh frm
        EOT
  }
  depends_on = [
{%- for key in terraform_resources %}
    {{key}},
{%- endfor %}  
    null_resource.custom_dependency,  
    null_resource.tf_env  
  ]

  triggers = {
    always_run = "${timestamp()}"
  }      
}

{%- if terraform_resources_part2|length>0 %}
# PART2
#
# In case like instance_pool, oke, function, container_instance, ...
# More terraform resources need to be created after build_deploy.
# Reread the env variables
data "external" "env_part2" {
  program = ["cat", "${local.project_dir}/target/resource_manager_variables.json"]
  depends_on = [
    null_resource.build_deploy
  ]
}
{%- endif %}

## AFTER_BUILD
# Last action at the end of the build
resource "null_resource" "after_build" {
  provisioner "local-exec" {
    command = <<-EOT
        cd ${local.project_dir}    
        export CALLED_BY_TERRAFORM="true"        
        . ./starter.sh env    
        if [ "$TF_VAR_tls" != "" ]; then
            title "Certificate - Post Deploy"
            certificate_post_deploy 
        fi

        $BIN_DIR/add_api_portal.sh

        title "Done"
        $PROJECT_DIR/src/done.sh          
        EOT
  }
  depends_on = [
{%- for key in terraform_resources_part2 %}
    {{key}},
{%- endfor %}      
    null_resource.build_deploy
  ]

  triggers = {
    always_run = "${timestamp()}"
  }    
}

data "local_file" "done_txt" {
  filename = "${local.project_dir}/target/done.txt"
  depends_on = [
    null_resource.after_build
  ]
}

# OUTPUT done.txt
output "done" {
    value = data.local_file.done_txt.content
}

# BEFORE_DESTROY
resource "null_resource" "before_destroy" {
  provisioner "local-exec" {
      when = destroy
      command = <<-EOT
        if [ ! -f starter.sh ]; then 
          cd ../..
        fi
        ./starter.sh destroy --called_by_resource_manager
        EOT
  }

  depends_on = [  
    null_resource.after_build
  ]
}
